### ISSUE TITLE
white border in button-groups

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [zurb/foundation#6641] opened 2015-06-20 15:19 UTC
hi,

in my button-group the border looks very ugly.
It seams that the parent-element of the .button cuts the border sometimes.
So I have fix it with this:

<pre>/* fix the border inside the li tag */
.button-group > li {
  float: left;
}
.button-group > li > button, 
.button-group > li .button {
  border-left: 1px solid rgba(255, 255, 255, 0.5);
}</pre>

<h3>SCSS</h3>
I suppose it can be easily fixed with: 
https://github.com/zurb/foundation/blob/master/scss/foundation/components/_button-groups.scss#L164
<pre> > li { @include button-group-style(); float: left;  }</pre>
and:    <br>
https://github.com/zurb/foundation/blob/master/scss/foundation/components/_button-groups.scss#L39
<pre>
  > button, .button {
    border-#{$default-float}: $button-group-border-width solid;
    border-#{$default-float}-color: rgba(255, 255, 255, .5);
  }
</pre>

But I haven't check the other cases an relations yet.
Hope you can use it...

**Comment by jnemeth** [comment] 2015-07-09 22:45
We're having trouble reproducing the issue, could you maybe throw up a codepen to demonstrate?  http://codepen.io/jnemeth/pen/oXdWRp

**Comment by MoniqueHahnefeld** [comment] 2015-07-19 10:07
Here is a screenshot from my browser, Chrome 43.0.2357.134 (64-bit), MacBook Air (13 Zoll, Mitte 2011), OSX 10.10.4 :
In other Browser seems to be the same. I tested also in Safari. You can the white space after the second button.

![white-lines-btn-bare](https://cloud.githubusercontent.com/assets/2779282/8765505/96367b9e-2e0e-11e5-8eab-953d05018b3e.png)

**Comment by jnemeth** [comment] 2015-07-20 21:03
I see what you mean.  This is due to the fact that different browsers have different default margins for some tags.  If you were to open that up in Firefox for example, you'd see the second and third right sides of the button have additional space.

This is fixed in the upcoming Foundation 6.

I did some quick testing, and noticed reset css actually does a good job of fixing it for now in 5: https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.css

**Closed by jnemeth** 2015-07-20 21:03 UTC
