### ISSUE TITLE
Tabs callback fires twice on second click

### ISSUE THREAD

**Issue by lukedanielson** [zurb/foundation#6009] opened 2014-11-04 19:22 UTC
Having an odd issue where the tabs callback fires twice, on every instance after the first instance of clicking any of the tabs:

JS:

```javascript
var $submitFormTabs = $('#submit-form-tabs');

    $submitFilmFormTabs.on('toggled', function (event, tab) {
        console.log(tab);
    });
```

Markup:

```html
<dl id="submit-form-tabs" class="tabs" data-tab>
  <dd class="active"><a href="#panel1">One</a></dd>
  <dd><a href="#panel2">Two</a></dd>
  <dd><a href="#panel3">Three</a></dd>
</dl>
<div class="tabs-content">
  <div class="content active" id="panel1">
    <p>This is the first panel of the basic tab example. This is the first panel of the basic tab example.</p>
  </div>
  <div class="content" id="panel2">
    <p>This is the second panel of the basic tab example. This is the second panel of the basic tab example.</p>
  </div>
  <div class="content" id="panel3">
    <p>This is the third panel of the basic tab example. This is the third panel of the basic tab example.</p>
  </div>
</div>
```

First click logs:

```bash
[div#panel1.content.active, jquery: "2.1.1", constructor: function, selector: "", toArray: function, get: function…]
```

Second click logs:

```bash
[div#panel2.content.active, jquery: "2.1.1", constructor: function, selector: "", toArray: function, get: function…] 
[div#panel2.content.active, jquery: "2.1.1", constructor: function, selector: "", toArray: function, get: function…]
```

Doesn't matter which tab get's clicked on the second instance...it fires twice no matter what.

Any ideas as to why?

**Comment by tomfriedhof** [comment] 2015-01-04 09:39
Yeah, commenting out line 50 fixes the issue for me.  What's odd is that reverting this patch back to what the code was before, makes my tabs disappear for some reason on change. https://github.com/zurb/foundation/commit/eaf28101d0be566e85cb0bcfd0f30a53e608348b

Here is a quick fix for the issue, but I think this issue needs to be looked at closer to come up with a better solution.
https://github.com/tomfriedhof/foundation/commit/8fd2f3b23b41bc8eab2327abcf4c58a5e392709b

**Comment by connormckelvey** [comment] 2015-01-19 18:49
This issue is really a bummer. The solution above is great if you are ok with modifying the source code. But for anyone using something like bower, modifying the source code is an iffy solution, as you may overwrite it. 

This solution is definitely more hackish than the one listed above, but it does not require modifying foundations source.

```javascript
        var toggleCounter = 0;
        $('#tabs').on('toggled', function (event, tab) {
          toggleCounter++;
          
          if(toggleCounter % 2 !== 0) {
            return;
          }
          console.log(event);
        });

**Comment by tomfriedhof** [comment] 2015-01-19 19:36
Using bower actually makes hacking the upstream version much easier.  All you have to do is fork the foundation repo, and then reference your fork in bower.json

```json
{
  "name": "My Cool App",
  "version": "0.0.0",
  "dependencies": {
    "foundation": "https://github.com/tomfriedhof/foundation.git#tabs-trigger"
  }
}
```

Once the issue is resolved upstream, just change your foundation version back to the version tag you want to checkout.

**Comment by mois3x** [comment] 2015-02-08 22:00
Same issue here, still no fix?

**Comment by wandl** [comment] 2015-02-11 02:28
I really need a quick fix for this also... as the toggled event actually loads the ajax into the tab content this is really bad...

**Closed** 2015-02-11 03:14 UTC
Labels: tabs

**Comment by wandl** [comment] 2015-02-11 03:16
Does this also fix the #5383 (deep_linking:true) firing ikt another two times?

**Comment by jeaniec** [comment] 2015-02-11 03:39
@wandl I was not aiming to fix that problem, so I can't be sure at this time, but you're welcome to test it out and let me know!

**Comment by wandl** [comment] 2015-02-11 05:01
@jeaniec I installed the master branch and tested and can confirm is working and also resolves #5383, thankyou for the fix!

**Comment by jeaniec** [comment] 2015-02-11 17:04
@wandl great!

**Comment by proimage** [comment] 2015-04-30 10:31
I'm still getting multiple event triggers with Foundation v5.5.1. I'm also getting event triggers when an already-active tab is clicked (when listening for the `'toggled'` event). What am I doing wrong?

**Comment by wandl** [comment] 2015-05-22 06:40
This has come back for me as well fires twice per toggled (click) in 5.5.1, also in some cases goes into a endless loop...

**Comment by proimage** [comment] 2015-05-22 07:57
For what it's worth, until this is fixed, I've resorted to using the ["checkbox hack" (actually radio buttons in this case) to create tabs](https://css-tricks.com/functional-css-tabs-revisited/).
