### ISSUE TITLE
[5.2.2] accordion and equalizer

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [zurb/foundation#6712] opened 2015-07-19 10:22 UTC
Hi,
I have problem with the equalizer if I open an accordion content.
I think the equalizer have had to update the value of the inline-style height, if I open or close an accordion content section.
Is that a known behavior or can I use some api to solve the problem?

http://codepen.io/MoniqueHahnefeld/pen/YXjJaG?editors=101

thx

**Comment by jerstew** [comment] 2015-08-03 04:53
I think the problem is that you're setting equalizer "data-equalizer-watch" on the **accordion parent**, which gives the accordion a fixed height. When you open a taller accordion panel, the parent height exceeds the aforementioned fixed height and overlaps with your footer. This is simply a conflict with the height calculations.

You might trying adding a simple equalizer 'reflow' on the accordion's 'toggle' callback:

    $('.accordion').on('toggled', function (event, accordion) {
        $(document).foundation('equalizer', 'reflow');
    });

**Comment by zurbrandon** [comment] 2015-09-22 17:33
Thanks @jerstew a reflow would be recommended here and will recalculate the equalized height of the items. This should solve this issue, so I'll close it. Feel free to reopen if I'm mistaken.

**Closed by zurbrandon** 2015-09-22 17:33 UTC
