### ISSUE TITLE
F4Apps version 1.1.0 breaks foundation-apps watch

### ISSUE THREAD

**Issue by quook** [zurb/foundation#6477] opened 2015-04-16 17:51 UTC
Running gulpfile works fine. Running foundation-apps watch causes error:

Error: foundation-apps-template@1.1.0 start: `gulp ""`
Exit status 1
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/lifecycle.js:213:16)
    at EventEmitter.emit (events.js:110:17)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/spawn.js:14:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by gakimball** [comment] 2015-04-16 21:13
Duplicate of zurb/foundation-apps#586

**Closed by gakimball** 2015-04-16 21:13 UTC
