### ISSUE TITLE
Topbar Keyboard Accessibility - Shift+Tab from Active dropdown stays open

### ISSUE THREAD

**Issue by justrhysism** [zurb/foundation#6594] opened 2015-06-01 07:29 UTC
Shift-tabbing out of active dropdown doesn't close dropdown.

#### Repro:

1. [Tab] to Top Bar with dropdowns ([occurs in the docs](http://foundation.zurb.com/docs/components/topbar.html))
2. [Tab] through to second or third top-level item with `has-dropdown`
3. Press [Enter] - (activates `active` state)
4. [Shift] + [Tab] to step back to previous dropdown

#### Expected result:
The dropdown you're navigating away from should close when the previous navigation opens.

#### Actual result:
The dropdown you're navigating away from stays open.

**Comment by Owlbertz** [comment] 2015-06-25 12:40
Hi. What browser are you using when encountering this issue? I am not able to reproduce this with Chrome...

**Comment by rafibomb** [comment] 2015-10-12 21:07
Not able to reproduce this either. Would really like to know if there still is an issue. We'll close this here. Open a new issue if anyone can reproduce this.

**Closed by rafibomb** 2015-10-12 21:07 UTC
