### ISSUE TITLE
text not centered for postfix aligned button when tiny

### ISSUE THREAD

**Issue by chuckakung** [zurb/foundation#6595] opened 2015-06-01 18:23 UTC
on a submit button that is postfix and tiny, the text is not centered vertically.  aligned along bottom of button.

**Comment by brianlenz** [comment] 2015-07-03 00:09
This is quite possibly caused by the bug that was fixed in this commit:

https://github.com/zurb/foundation/commit/676bcb7d789ab323336657e1615b3f722a9c6433

**Comment by myndzi** [comment] 2015-08-25 19:36
The bower package for foundation version 5.5.2 still contains this error.

**Comment by zurbrandon** [comment] 2015-09-22 02:50
I'm using the most recent CDN here and not seeing the issue arise. This may have been fixed by another PR or fix, so I'll close this for now, but feel free to reopen if I'm misunderstanding

http://codepen.io/zurbrandon/pen/oXajqZ?editors=110

Thanks!

**Closed by zurbrandon** 2015-09-22 02:50 UTC

**Comment by myndzi** [comment] 2015-09-22 03:10
The bower package for foundation 5.5.2 still contains the error...

```
$ bower install foundation
$ grep "postfix.button" bower_components/foundation/scss/foundation/components/_forms.scss
    .postfix.button { @include button-size(false, false); @include postfix(false, false, true); }
```
Three arguments where there should be four.

**Comment by myndzi** [comment] 2015-09-28 15:05
@zurbrandon ?
