### ISSUE TITLE
Abide validation throws card error even when number is valid

### ISSUE THREAD

**Issue by WebTerminator** [zurb/foundation#6067] opened 2014-11-27 11:44 UTC
If I type the card number fist in my form (tested with my own VISA) and than I click on submit I still get an error that the card number is invalid. However if I start filling the form from the top down with the same card number and I click on submit than it's fine. :O

Here is my link: http://alessandrosantese.com/abide/index3.html

I have also overwritten the card pattern with my own visa regex.

    <form data-abide="ajax" id="myform">

      <div class="name-field row panel input-wrapper">
        <label>Your name <small>required</small>
          <input type="text" required>
        </label>
        <small class="error">Name is required and must be a string.</small>
      </div>

      <div class="email-field row panel input-wrapper">
        <label>Email <small>required</small>
          <input type="email" required>
        </label>
        <small class="error">An email address is required.</small>
      </div>

      <div class="card-field row panel input-wrapper">
        <label>Card number <small>required</small>
          <input type="text" pattern="card" autocomplete="off" required>
        </label>
        <small class="error">An email address is required.</small>
      </div>

      <div class="email-field row panel">

        <button type="submit">Submit</button>

      </div>

    </form>

    
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.js"></script>
    <script src="js/foundation.min.js"></script>
    <script>
    $(document)
      .foundation({
        abide : {
          patterns: {
            dashes_only: /^[0-9-]*$/,
            ip_address: /^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/,
            card:/^4(?:[0-9]{12}|[0-9]{15})/
          }
        }
      });
    </script>

**Comment by regdoug** [comment] 2015-02-22 19:18
Also, I'm seeing in @WebTerminator 's example that all fields are marked with errors if the name field is invalid.

**Comment by regdoug** [comment] 2015-02-22 21:07
I wrote some Jasmine tests that run through all the possible combinations of valid/invalid/no inputs and in every possible order, but I couldn't reproduce the error.  If you are interested, you can check out https://github.com/regdoug/foundation/blob/abide-order-testing/spec/abide/alessandro.js  The code is pretty ugly, but I'm pretty sure the tests are correct, and all 162 are passing.

**Comment by jeaniec** [comment] 2015-02-26 02:46
I tried to replicate this error on my local machine but could not. I'm also finding that the tests are passing, as @regdoug had found. Closing this issue for now.

**Closed by jeaniec** 2015-02-26 02:46 UTC
Labels: abide
