### ISSUE TITLE
Topbar JS Duplicating Menu Item on Medium Screens.

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation#6459] opened 2015-04-10 23:05 UTC
I came across what I would say is a bug with the Topbar.

Take a look at this screenshot:

![nla-foundation-menu](https://cloud.githubusercontent.com/assets/1938824/7098835/b5b78436-dfa3-11e4-9fd2-5711f83e69e5.jpg)

You will see the Main Menu Link is called "Puppies" but right below that is another link called "Puppies". This is a duplicate of the main menu link. When I inspect the code here is what I see:

    <li class="parent-link hide-for-large-up"><a class="parent-link js-generated" href="#">Puppies</a></li>

So the JS is generating the link. In my situation the class should be `hide-for-medium-up` not large. I can manually fix this but this shouldn't happen.

Note: On large screens everything is fine.

**Comment by rafibomb** [comment] 2015-04-25 00:17
Looks like a duplicate of this https://github.com/zurb/foundation/issues/6393

Fixed for 5.5.2 coming next week

**Closed by rafibomb** 2015-04-25 00:17 UTC
