### ISSUE TITLE
Foundation abide 5.5 ajax submit duplicated

### ISSUE THREAD

**Issue by diskman** [zurb/foundation#6123] opened 2014-12-17 14:47 UTC
http://stackoverflow.com/questions/27528108/foundation-abide-5-5-ajax-submit-duplicated

**Comment by hdra** [comment] 2015-01-15 14:02
seems to be duplicate of #5392

**Comment by rafibomb** [comment] 2015-02-13 22:18
Closing for #5392

**Closed by rafibomb** 2015-02-13 22:18 UTC
Labels: abide
