### ISSUE TITLE
Foundation crash when enable html compression (i.e delete all spaces between tags)

### ISSUE THREAD

**Issue by DenisNeustroev** [zurb/foundation#6661] opened 2015-06-29 10:47 UTC
tested at least Foundation Forms

**Comment by gakimball** [comment] 2015-06-30 17:16
Could you give us more details?

- What operating system and browser?
- What page crashed?
- What tool are you using to compress HTML, with what options?

We need a way to reproduce it so we can better help you out.

**Comment by rafibomb** [comment] 2015-10-12 20:13
We'll need more details to help you out. Since no one else has reported it here we'll close this. 

The Foundation forum would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Closed by rafibomb** 2015-10-12 20:13 UTC
